#!/bin/sh

# Copyright © 2013-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
if [ $# -ne 1 ]
then
    printf 'Usage: %s TTY\n' "${0##*/}" >&2
    exit 1
fi
tty="$1"
printf 'AT^RESET\r\n' > "$tty"

# vim:ts=4 sts=4 sw=4 et
