#!/bin/sh

# Copyright © 2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

confdir=${XDG_CONFIG_HOME:-$HOME/.config}/gammu
variants=$(
    find -- "$confdir" -mindepth 1 -maxdepth 1 -name 'config-*' -printf '%f\n' |
    sort |
    sed -e 's/^config-//g' |
    tr '\n' ' '
)
variants=${variants% }

bad_usage()
{
    prog=${0##*/}
    printf "Usage: %s VARIANT COMMAND [ARGS...]\n" "$prog" >&2
    printf 'Variants: %s\n' "$variants" >&2
    exit 1
}

[ $# -ge 2 ] || bad_usage

variant="$1"
shift
config="$confdir/config-$variant"
[ -f "$config" ] || bad_usage
exec bwrap \
    --dev-bind / / \
    --ro-bind "$config" "$confdir"/config \
    "$@"

# vim:ts=4 sts=4 sw=4 et
