#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2013-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from __future__ import print_function

import argparse
import re

import messaging.utils

def main():
    cusd_match = re.compile('[+]CUSD: 0,"([^"]+)"').match
    ap = argparse.ArgumentParser()
    ap.add_argument('device', metavar='DEVICE')
    options = ap.parse_args()
    with open(options.device, 'r+b', 0) as tty:
        tty.write('AT+CUSD=1,"AA182C3602",15\r')
        tty.flush()
        while 1:
            line = tty.readline().rstrip()
            if not line:
                continue
            if line.startswith('^'):
                continue
            match = cusd_match(line)
            if match is None:
                print('#', line)
            else:
                s = match.group(1)
                s = messaging.utils.unpack_msg(s)
                print(s)
                break
        tty.write('AT+CUSD=0\r')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
