#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import types

import gammu

lambda: (yield from 0)  # Python >= 3.3 is required

def dial(ctxt, n):
    def callback(sm, cb_type, data):
        nonlocal reply
        if cb_type != 'USSD':
            raise RuntimeError('unexpected callback type: {tp}'.format(tp=cb_type))
        reply = dict(data)
    if ctxt.debug:
        print('>>>', n)
    sm = ctxt.sm
    sm.SetIncomingUSSD()
    sm.SetIncomingCallback(callback)
    try:
        sm.DialService(n)
        reply = None
        while reply is None:
            sm.ReadDevice()
        return reply
    finally:
        sm.SetIncomingCallback(None)

networks = [
    'pl-t-mobile',
    'pl-play',
]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-c', '--config')
    ap.add_argument('-n', '--network', required=True, choices=networks)
    ap.add_argument('--debug', action='store_true')
    options = ap.parse_args()
    sm = gammu.StateMachine()
    kwargs = {}
    if options.config is not None:
        kwargs.update(Filename=options.config)
    sm.ReadConfig(**kwargs)
    sm.Init()
    do = globals()['do_' + options.network.replace('-', '_')]
    ctxt = types.SimpleNamespace(
        sm=sm,
        debug=options.debug,
    )
    do(ctxt)

def dial_101(ctxt):
    reply = dial(ctxt, '*101#')
    text = reply['Text']
    print(text)
    if reply['Status'] == 'NoActionNeeded':
        return
    else:
        raise NotImplementedError

def dial_140_1(ctxt):
    # PL T-Mobile
    reply = dial(ctxt, '*140*1##')
    while True:
        text = reply['Text']
        print(text)
        status = reply['Status']
        if status == 'NoActionNeeded':
            return
        elif status == 'ActionNeeded':
            pass
        else:
            raise NotImplementedError
        lines = text.splitlines()
        if '1. . Dalej' in lines:
            reply = dial(ctxt, '1')
            continue
        if '9. Koniec' in lines:
            reply = dial(ctxt, '9')
            continue
        raise NotImplementedError

def do_pl_t_mobile(ctxt):
    dial_101(ctxt)
    dial_140_1(ctxt)

def do_pl_play(ctxt):
    dial_101(ctxt)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
